/**
 * IMAGE OPTIMISATION — assets-original/ → public/assets/
 *
 * Recursively converts PNG/JPG sources to production WebP (optional AVIF),
 * generating responsive sizes with aspect ratio preserved.
 *
 *   portraits (h > w):  400 / 800 / 1200 px wide
 *   landscape  (w >= h): 800 / 1200 / 1600 px wide
 *
 * - never enlarges originals (withoutEnlargement)
 * - skips sources whose mtime+size are unchanged and whose outputs exist
 * - preserves folder structure under public/assets/
 * - filenames are slugified (spaces → '-', lowercase) — clean URLs
 * - writes scripts/image-map.json mapping every source → production base URL
 *
 * Usage:
 *   npm run optimize-images            (WebP only)
 *   npm run optimize-images -- --avif  (also AVIF)
 *   npm run optimize-images -- --force (ignore cache, reprocess all)
 */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.resolve(__dirname, '..');
const SRC_ROOT = path.join(ROOT, 'assets-original');
const OUT_ROOT = path.join(ROOT, 'public', 'assets');
const MANIFEST = path.join(__dirname, '.image-manifest.json');
const MAP_FILE = path.join(__dirname, 'image-map.json');

const WITH_AVIF = process.argv.includes('--avif');
const FORCE = process.argv.includes('--force');

const PORTRAIT_SIZES = [400, 800, 1200];
const LANDSCAPE_SIZES = [800, 1200, 1600];
const WEBP_QUALITY = 82;
const AVIF_QUALITY = 60;

const slugify = (name) =>
  name
    .replace(/\.[^.]+$/, '')           // strip extension
    .trim()
    .replace(/['’]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase();

const loadManifest = () => {
  try { return JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); } catch { return {}; }
};

const walk = (dir) =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : [p];
  });

const manifest = loadManifest();
const map = {};
let processed = 0, skipped = 0, failed = 0;

const sources = walk(SRC_ROOT).filter((p) => {
  const ext = path.extname(p).toLowerCase();
  return ['.png', '.jpg', '.jpeg'].includes(ext);
});

if (sources.length === 0) {
  console.error('No PNG/JPG sources found under assets-original/');
  process.exit(1);
}

(async () => {
  for (const src of sources) {
    const rel = path.relative(SRC_ROOT, src);
    const stat = fs.statSync(src);
    const stamp = { mtime: Math.round(stat.mtimeMs), size: stat.size };

    // slugified output base: assets/<subdir>/<slug>
    const relDir = path.dirname(rel);
    const base = path.join('assets', relDir, slugify(path.basename(src)));
    const outBase = path.join('public', base);

    const sizes = await sharp(src).metadata().then((m) =>
      m.height > m.width ? PORTRAIT_SIZES : LANDSCAPE_SIZES
    ).catch(() => null);
    if (!sizes) { console.error(`SKIP (unreadable): ${rel}`); failed++; continue; }

    const outputs = sizes.flatMap((w) => [
      `${outBase}-${w}.webp`,
      ...(WITH_AVIF ? [`${outBase}-${w}.avif`] : []),
    ]);

    const cached = !FORCE &&
      manifest[rel] &&
      manifest[rel].mtime === stamp.mtime &&
      manifest[rel].size === stamp.size &&
      outputs.every((o) => fs.existsSync(path.join(ROOT, o)));

    if (cached) { skipped++; map[rel.replaceAll('\\', '/')] = '/' + base.replaceAll('\\', '/'); continue; }

    fs.mkdirSync(path.dirname(path.join(ROOT, outBase)), { recursive: true });
    try {
      for (const w of sizes) {
        const img = sharp(src).resize({ width: w, withoutEnlargement: true });
        await img.webp({ quality: WEBP_QUALITY, effort: 4 }).toFile(path.join(ROOT, `${outBase}-${w}.webp`));
        if (WITH_AVIF) {
          await img.avif({ quality: AVIF_QUALITY, effort: 2 }).toFile(path.join(ROOT, `${outBase}-${w}.avif`));
        }
      }
      manifest[rel] = stamp;
      processed++;
      map[rel.replaceAll('\\', '/')] = '/' + base.replaceAll('\\', '/');
      console.log(`ok  ${rel} → ${sizes.join('/')} webp${WITH_AVIF ? ' + avif' : ''}`);
    } catch (err) {
      console.error(`FAIL ${rel}: ${err.message}`);
      failed++;
    }
  }

  fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2));
  fs.writeFileSync(MAP_FILE, JSON.stringify(map, null, 2));

  // photo manifest for the Team Archive — which portraits exist
  const slugRe = /(?:^|[/\\])team-photos[/\\](.+)-\d+\.webp$/;
  const slugs = [...new Set(
    Object.values(map)
      .map((u) => { const m = String(u).match(slugRe); return m ? m[1] : null; })
      .filter(Boolean)
  )].sort();
  const manifestTs = path.join(ROOT, 'src', 'data', 'photo-manifest.ts');
  fs.mkdirSync(path.dirname(manifestTs), { recursive: true });
  fs.writeFileSync(manifestTs,
    '/** AUTO-GENERATED by scripts/optimize-images.cjs — do not edit by hand.\n' +
    ' * Slugs of member portraits that exist as optimized WebP assets.\n' +
    ' * Regenerate with: npm run optimize-images */\n' +
    'export const PHOTO_SLUGS: string[] = ' + JSON.stringify(slugs, null, 2) + ';\n');

  console.log(`\n${processed} processed, ${skipped} up-to-date, ${failed} failed`);
  console.log(`map: scripts/image-map.json`);
})();
